name: Build PaperP

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-exe:
    strategy:
      matrix:
        include:
          - arch: 'x64'
            python-arch: 'x64'
            name_suffix: 'x64'
          - arch: 'x86'
            python-arch: 'x86'
            name_suffix: 'x86'
            
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        architecture: ${{ matrix.python-arch }}
        
    - name: Install dependencies
      shell: powershell
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install nuitka
        # Install zstandard only for x64 to avoid memory errors on x86 (32-bit Python)
        if ("${{ matrix.arch }}" -eq "x64") {
          pip install zstandard
        }
        
    - name: Build with Nuitka
      run: |
        python -m nuitka --standalone --onefile --include-package=src --include-package=scapy --output-dir=dist --output-filename=PaperP-${{ matrix.name_suffix }}.exe --windows-uac-admin --assume-yes-for-downloads --remove-output src/main.py
        
    - name: Upload EXE File
      uses: actions/upload-artifact@v4
      with:
        name: PaperP-Windows-${{ matrix.name_suffix }}
        path: dist/PaperP-${{ matrix.name_suffix }}.exe

  package-source:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Zip Source Code
      run: |
        zip -r PaperP-Source.zip src requirements.txt README.md
        
    - name: Upload Source Artifact
      uses: actions/upload-artifact@v4
      with:
        name: PaperP-Source
        path: PaperP-Source.zip
